export const COMMENT_TEXTAREA_COLLAPSED_HEIGHT = '44px';
export const COMMENT_TEXTAREA_EXPANDED_HEIGHT = '120px';
export const COMMENT_TEXTAREA_EXPANDED_MAX_HEIGHT = '15rem';
export const COMMENT_FOCUS_DELAY_MS = 150;
