name: CI

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: development
      deployment: false
    env:
      NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}
      NEXT_PUBLIC_ENV: ${{ vars.NEXT_PUBLIC_ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.11.0'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate API client
        run: pnpm api:generate
      - name: Format check
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
      - name: Type check
        run: pnpm type-check
      - name: Test
        run: pnpm test
